services:
  - type: web
    name: langchain-agent
    region: frankfurt
    runtime: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    # Jeśli w Dockerfile jest prawidłowe CMD, to startCommand można usunąć.
    startCommand: "uvicorn app.api.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: REDIS_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        sync: false
      - key: TWILIO_WHATSAPP_TO
        sync: false
      - key: TWILIO_WHATSAPP_CONTENT_SID
        sync: false
      - key: FETCH_BASE_URL
        value: "https://fetch-2-0.onrender.com"
      - key: PREFERENCES_XLSX_PATH
        value: "./data/tablica.xlsx"
      - key: WOJEWODZTWA_MAPPING_PATH
        value: "./data/wojewodztwa_mapping.json"
